# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 14:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TVLikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('likes_n', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TvShowEpModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tve_name', models.CharField(max_length=100)),
                ('tve_season', models.IntegerField()),
                ('tve_ep_number', models.IntegerField()),
                ('tve_airdate', models.CharField(max_length=100)),
                ('tve_airtime', models.CharField(max_length=100)),
                ('tve_img_ep', models.CharField(max_length=100)),
                ('tve_runtime', models.FloatField()),
                ('tve_summary', models.TextField(max_length=400)),
                ('tve_summary_br', models.TextField(blank=True, default='', max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='TvShowModel',
            fields=[
                ('tvs_id', models.IntegerField(primary_key=True, serialize=False)),
                ('tvs_name', models.CharField(max_length=100)),
                ('tvs_name_br', models.CharField(blank=True, default='', max_length=100)),
                ('tvs_genre', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('tvs_language', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('tvs_status', models.CharField(max_length=100, null=True)),
                ('tvs_runtime', models.FloatField(blank=True, default='', null=True)),
                ('tvs_schedule', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('tvs_rating', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('tvs_timezone', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('tvs_imdb_id', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('tvs_img_m_url', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('tvs_summary', models.TextField(blank=True, default='', max_length=100, null=True)),
                ('tvs_summary_br', models.TextField(blank=True, default='', max_length=100, null=True)),
                ('tvs_likes', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='tvshowepmodel',
            name='tvshowmodel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.TvShowModel'),
        ),
        migrations.AddField(
            model_name='tvlikes',
            name='likes_episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.TvShowEpModel'),
        ),
        migrations.AddField(
            model_name='tvlikes',
            name='likes_tvshow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.TvShowModel'),
        ),
    ]
